[project]
name = "stomatapy"
version = "0.1.0"
description = "StomataPy: Datasets and Generalized Models for Leaf Epidermal Segmentation"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fairscale>=0.4.13",
    "ftfy>=6.3.1",
    "hdbscan>=0.8.40",
    "jupyter>=1.1.1",
    "more-itertools>=10.7.0",
    "numpy==1.26.4",
    "opencv-python>=4.11.0.86",
    "openmim==0.3.8",
    "openpyxl>=3.1.5",
    "pycocotools>=2.0.10",
    "regex>=2025.7.34",
    "sahi>=0.11.32",
    "scikit-image>=0.25.2",
    "torch==2.1.1",
    "torchvision==0.16.1",
    "transformers==4.41.2",
    "xformers==0.0.23",
]

