---
title: "2024.02 S. oleracea trial 24 h starch dynamics"
author: "Hongyuan Zhang"
format: html
execute: 
  cache: true
editor: visual
jupyter: python3
editor_options: 
  chunk_output_type: inline
---

```{r}
#| label: setup
#| echo: false
#| message: false
options(warnParticalMatchDollar = TRUE)  # warning $ partial matching
options(warnParticalMatchArgs = TRUE)  # warning func args partial matching

library('tidyverse')  # a collection of R packages designed for data science
library('ggthemes')  # includes colorblind safe color palette
library('rlang')  # functions for base types and core R and 'Tidyverse' features

save_dir = './/asserts'  # output directory
```

## Load data from all datasets

```{r}
#| label: data wrangling
#| echo: false
#| message: false
#| warning: false
#| fig.height: 8
#| fig.width: 8 * 1.618

data_sheet_path <- 'Datasets//Dataset_summary.xlsx'

stomata_data <- readxl::read_excel(data_sheet_path) %>%
    dplyr::mutate(
        dplyr::across(
            c(`Image scale (pixels/μm)`, `Mean stomatal area (μm²)`,
              `Mean stomatal complex area (μm²)`, `Stomatal index`,
              `Mean pavement cell area (μm²)`, `Stomatal density (mm⁻²)`
              ), as.numeric
            )
        ) %>%
    dplyr::mutate_if(is.character, factor) %>%
    dplyr::mutate(
        `Lineage_Clade` = factor(paste(Lineage, Clade, sep = ' - ')),
        `Mean stomatal complex area (μm²)` = dplyr::if_else(
            `Stomata type` == 'Anomocytic',
            `Mean stomatal area (μm²)`,
            `Mean stomatal complex area (μm²)`
            )
        ) %>% 
    # dplyr::filter(`Dataset` != 'Vofely2019') %>%
    dplyr::group_by(
        Species, `Sampling method`, `Image modality`, `Image quality`, 
        `Lineage`, `Clade`, `Family`, `Genus`, `Stomata type`,
        `Lineage_Clade`
        ) %>%
    summarise(
        `Stomatal complex area per species (μm²)` = mean(`Mean stomatal complex area (μm²)`, na.rm = TRUE),
        `Stomatal density per species (mm⁻²)` = mean(`Stomatal density (mm⁻²)`, na.rm = TRUE),
        `Pavement cell area per species (μm²)` = mean(`Mean pavement cell area (μm²)`, na.rm = TRUE),
        `Stomatal complex area / pavment cell area` = mean(
            `Stomatal complex area per species (μm²)` / `Pavement cell area per species (μm²)`
        ),
        `Stomatal index per species` = mean(`Stomatal index`, na.rm = TRUE),
        .groups = 'drop'
        ) %>% 
    dplyr::filter(`Stomatal complex area per species (μm²)` < 2000) %>%
    dplyr::filter(`Stomatal density per species (mm⁻²)` < 1600)
    # dplyr::filter(`Stomatal index per species` < 0.3)
```

## **Plot data**

```{r}
#| label: stomata density vs stomatal complex area
#| echo: false
#| message: false
#| warning: false
#| fig.height: 8
#| fig.width: 8 * 1.618



plot_stomata <- function(stomata_data, variable_x, variable_y) {
    # This function plot variable_x against variable_y
    ggplot2::ggplot(
        data = stomata_data, 
        mapping = ggplot2::aes(
            x = {{ variable_x }}, 
            y = {{ variable_y }},
        ) 
    ) +
        ggplot2::geom_point(
            ggplot2::aes(color = `Lineage_Clade`),
            alpha = 0.4, 
            size = 4
        ) +
        ggplot2::geom_smooth(method = 'loess', formula = y ~ x, show.legend = FALSE, color = 'black') +
        ggthemes::scale_color_colorblind() +
        ggplot2::theme_bw() +
        ggplot2::theme(
            plot.margin = margin(t = 30, r = 60, b = 30, l = 60),
            panel.background = ggplot2::element_blank(), 
            panel.border = ggplot2::element_rect(color = 'black', fill = NA, linewidth = 1),
            legend.position = c(0.7, 0.8),
            legend.title = ggplot2::element_blank(),
            legend.text = ggplot2::element_text(size = 21),
            legend.key = ggplot2::element_blank(), 
            legend.background = ggplot2::element_blank(), 
            legend.box.background = ggplot2::element_blank(),
            legend.key.size = ggplot2::unit(2, 'line'), 
            axis.title.x = ggplot2::element_text(size = 27), 
            axis.title.y = ggplot2::element_text(size = 27), 
            axis.text.x = ggplot2::element_text(size = 25), 
            axis.text.y = ggplot2::element_text(size = 25), 
            strip.text = ggplot2::element_text(size = 25), 
            strip.background = ggplot2::element_rect(fill = 'grey98')
        )
}

plot_1 <- stomata_data |>
    plot_stomata(
        variable_x = `Stomatal complex area per species (μm²)`,
        variable_y = `Stomatal density per species (mm⁻²)`
    )

plot_2 <- stomata_data |>
    plot_stomata(
        variable_x = `Stomatal complex area per species (μm²)`,
        variable_y = `Pavement cell area per species (μm²)`
    )

plot_3 <- stomata_data |>
    plot_stomata(
        variable_x = `Stomatal complex area / pavment cell area`,
        variable_y = `Stomatal index per species`
    )


ggplot2::ggsave(
    plot = plot_1, 
    filename = paste(file.path(save_dir, 'Stomatal density vs Stomatal complex area.png')), 
    dpi = 500, 
    type = 'cairo', 
    height = 10, 
    width = 12
)

ggplot2::ggsave(
    plot = plot_2, 
    filename = paste(file.path(save_dir, 'Pavement cell area vs Stomatal complex area.png')), 
    dpi = 500, 
    type = 'cairo', 
    height = 10, 
    width = 12
)

ggplot2::ggsave(
    plot = plot_3, 
    filename = paste(file.path(save_dir, 'Stomatal complex and pavment cell ratio vs stomatal index.png')), 
    dpi = 500, 
    type = 'cairo', 
    height = 10, 
    width = 12
)
```
